### ISSUE TITLE
Having difficulty in making googletest using cmake, mingw

### ISSUE THREAD

**Issue by kimjohn89** [google/googletest#2418]
My environment: Windows 10 64 bit, MinGW, CMake 3.15.2, Python 3.7.
I followed the instruction and ran cmake. There was no problem.
```
C:\googletest-master>cd build

C:\googletest-master\build>cmake ../ -G "MinGW Makefiles"
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Users/sangjin/AppData/Local/Programs/Python/Python37-32/python.exe (found version "3.7.4")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/googletest-master/build
```

But when I used mingw32-make, I have the following problem.
```
C:\googletest-master\build>mingw32-make
Scanning dependencies of target gtest
[ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj
In file included from C:\googletest-master\googletest\src\gtest-all.cc:41:
C:/googletest-master/googletest/src/gtest.cc:86:11: fatal error: crtdbg.h: No such file or directory
 # include <crtdbg.h>  // NOLINT
           ^~~~~~~~~~
compilation terminated.
googletest\CMakeFiles\gtest.dir\build.make:62: recipe for target 'googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj' failed
mingw32-make[2]: *** [googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj] Error 1
CMakeFiles\Makefile2:171: recipe for target 'googletest/CMakeFiles/gtest.dir/all' failed
mingw32-make[1]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2
Makefile:139: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

C:\googletest-master\build>
```
Please, help me solve this problem.

**Comment by EricWF** [comment]
Was the build directory empty when you ran the `cmake` command in the first example?
Can you provide the full `CMakeCache.txt` produced by CMake?
Do you have a visual studio version installed?

I'm surprised other users haven't hit this bug before and reported it.

I don't have a MinGW enviroment to test in right now, so I can't promise I'll be able to help debug this alone.

**Comment by kimjohn89** [comment]
The build directory was empty when I ran the cmake command.
I want to use MinGW and Eclipse instead of using Visual Studio. Is Visual Studio required to build googletest on Windows. I think we should be able to build googletest on Windows without needing to install Visual Studio.

**Comment by ruslemo** [comment]
Same error here. I don't have visual studio and i'm not able to build gtest.

My environment: Windows 10 64 bit, MinGW, CMake 3.14.6, Python 2.7.

**Comment by pabloh1992** [comment]
I have the same error

_cmake -G "MSYS Makefiles"
make_

/googletest-master/googletest/src/gtest-all.cc:41:0:
/googletest-master/googletest/src/gtest.cc:86:32: fatal error: crtdbg.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/gtest.dir/src/gtest-all.cc.obj] Error 1
make[1]: *** [CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2

Environment: Windows 10 64 bit, MinGW, CMake 3.15.2, Python 3.5

**Comment by BarrettLowe** [comment]
I am having the same error when using the "MinGW Makefiles" generator as well as "Ninja". Seems like it's not related to the generator...?

**Comment by BarrettLowe** [comment]
@kimjohn89 , are you including googltest as an external project in cmake? That seems to be what's causing the problem for me... I can build the libraries raw no problem. But using the ExternalProject_Add function of cmake is causing problems for me.

**Comment by BarrettLowe** [comment]
> @kimjohn89 , are you including googltest as an external project in cmake? That seems to be what's causing the problem for me... I can build the libraries raw no problem. But using the ExternalProject_Add function of cmake is causing problems for me.

I'm a liar. Still can't build using clang. MinGW works fine but Clang still gives this error.

**Comment by nerudaj** [comment]
Same problem here. On CentOS7, project in attached zip works, on windows, the crtdgb.h error occures:

```
fatal error: crtdbg.h: No such file or directory
 # include <crtdbg.h>  // NOLINT
```

[repro.zip](https://github.com/google/googletest/files/3614829/repro.zip)

Is there any way to make gtest think I am not on Windows? MinGW behaves pretty much the same way as g++ on linux, I think it would work.

**Comment by vores8** [comment]
Also having the same problem. Win 10 64 bit, CMAKE 3.15.4, Python 2.7.16

```
D:\development\googletest>mingw32-make
[ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj
In file included from D:\development\googletest\googletest\src\gtest-all.cc:41:
D:/development/googletest/googletest/src/gtest.cc:86:11: fatal error: crtdbg.h: No such file or directory
 # include <crtdbg.h>  // NOLINT
           ^~~~~~~~~~
compilation terminated.
googletest\CMakeFiles\gtest.dir\build.make:62: recipe for target 'googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj' failed
mingw32-make[2]: *** [googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj] Error 1
CMakeFiles\Makefile2:181: recipe for target 'googletest/CMakeFiles/gtest.dir/all' failed
mingw32-make[1]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2
Makefile:139: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

```
Any meaningful response from maintainers since AUG 20?

**Comment by gennadiycivil** [comment]
Anything related to CMake is community supported. We do not use it internally and we are not in position to check or comment on these issues. In general the maintainers would look for community consensus.

**Comment by wujun198569** [comment]
Same problem with MinGW32 which doesn't have <crtdbg.h> in it.But I do found <crtdbg.h> in x64 version of MinGW(x86_64-4.9.2-posix-seh-rt_v3-rev1). After switch to x64 version MinGW,  gtest was built successfully.
I'm not quite sure why x64/x86 version of MinGW has such difference on <crtdbg.h>, maybe someone who knows the reason can give a solution for this problem.

**Comment by Sinclair-John** [comment]
Same Problem for me. The Problem came in with #2371 in line 86 of gtest.cc:
`# include <crtdbg.h>  // NOLINT`
crtdbg.h is not a C++ standard header and only supported by Visual Studio. As I see gtest has no macro for Windows Visual Studio so my suggestion would be:
```C++
#ifndef GTEST_OS_WINDOWS_MINGW
#include <crtdbg.h>  // NOLINT
#endif // GTEST_OS_WINDOWS_MINGW
```
A more clean solution but with more effort would be to define a GTEST_OS_WINDOWS_VS macro.

What you think? Would somebody gernerate a Pull Request?

**Comment by kaustubhharapanahalli** [comment]
I'm using Visual Studio Code and using the MinGW compiler throws me the error saying `crtdbg.h: No such file or directory`. But when I used Visual Studio Community 2019 Compiler for enabling the kit, the build worked seemlessly. 

I think gtest is not built for MinGW. So Windows users can use Visual Studio code and the Visual Studio Community Kit for building CMake.

**Comment by Sinclair-John** [comment]
@kaustubhharapanahalli why do you think that gtest is not built for MinGW?
Please have look at:
[https://github.com/google/googletest#platforms](https://github.com/google/googletest#platforms)
And for what it is the macro `GTEST_OS_WINDOWS_MINGW` for, when not for MinGW?

**Comment by kaustubhharapanahalli** [comment]
@Sinclair-John Sorry, I've fixed the comment.

**Comment by vores8** [comment]
@gennadiycivil 
ok. leaving CMAKE aside. I've got gtest code from the git. I would like to use it with MIGNW under WINDOWS (because GOOGLE claims that "Google test has been used on a variety of platforms: ... Windows ... MinGW ...")

So the question is: what is the sequence of steps that will allow me to use GOOGLETEST with MINGW under WINDOWS?

**Comment by Sinclair-John** [comment]
I made a PR #2521 
Feel free to test it.
👍

**Comment by mandyedi** [comment]
I still have the issue on Windows 10 with MinGW 32 bit version. I see that the gtest-port.cc was fixed to not include the crtdbg.h
```cpp
# ifdef _MSC_VER
#  include <crtdbg.h>
# endif  // _MSC_VER
```
but the gtest.cc was not. I fixed it and also discarded debugapi.h, then I got the following error:
__gtest.cc:863:29: error: 'int gettimeofday(timeval*, void*)' is deprecated [-Werror=deprecated-declarations]__
Maybe I do somthing wrong. I compiled it as below (in googletest/googletest folder):
```
mkdir build
cd build
cmake ../ -G "MinGW Makefiles"
mingw32-make
```

**Comment by kimjohn89** [comment]
Use mingw64 instead. Everything works fine when mingw64 is used.

**Comment by mandyedi** [comment]
I managed to compile with mingw64, thank you!

**Comment by Durgeshjoshi** [comment]
@mandyedi can you explain the process of how did you build google test for a window using mingw64.

**Comment by mandyedi** [comment]
@Durgeshjoshi these were the steps I followed:

Download MSYS2 and follow the instructions: https://www.msys2.org/  
 1. Run installer
 2. Start msys2
 3. pacman -Syu
 4. If needed, close MSYS2, run it again.
 5. Update the rest with: pacman -Su

Install MinGW64 https://stackoverflow.com/questions/30069830/how-to-install-mingw-w64-and-msys2  
 1. pacman -S mingw-w64-x86_64-gcc (32-bit: pacman -S mingw-w64-i686-gcc)

Build Google test
 1. Copy sourcode into c:\msys64\home\<username>
 2. From this point you should be able to run the following commands in the msys shell:
```
mkdir build
cd build
cmake ../ -G "MinGW Makefiles"
mingw32-make
```
